//# raylib 4.0 bindings.   Lgpl Licensed.  Source here: https://github.com/NotNotTech/Raylib-CsLo
//# Find Raylib+docs here:   https://github.com/raysan5/raylib/blob/master/src/raylib.h
//# This file, and it's containing folder are automatically generated.  Do not Modify.
namespace Raylib_CsLo
{
    public enum rlPixelFormat
    {
        RL_PIXELFORMAT_UNCOMPRESSED_GRAYSCALE = 1,
        RL_PIXELFORMAT_UNCOMPRESSED_GRAY_ALPHA,
        RL_PIXELFORMAT_UNCOMPRESSED_R5G6B5,
        RL_PIXELFORMAT_UNCOMPRESSED_R8G8B8,
        RL_PIXELFORMAT_UNCOMPRESSED_R5G5B5A1,
        RL_PIXELFORMAT_UNCOMPRESSED_R4G4B4A4,
        RL_PIXELFORMAT_UNCOMPRESSED_R8G8B8A8,
        RL_PIXELFORMAT_UNCOMPRESSED_R32,
        RL_PIXELFORMAT_UNCOMPRESSED_R32G32B32,
        RL_PIXELFORMAT_UNCOMPRESSED_R32G32B32A32,
        RL_PIXELFORMAT_COMPRESSED_DXT1_RGB,
        RL_PIXELFORMAT_COMPRESSED_DXT1_RGBA,
        RL_PIXELFORMAT_COMPRESSED_DXT3_RGBA,
        RL_PIXELFORMAT_COMPRESSED_DXT5_RGBA,
        RL_PIXELFORMAT_COMPRESSED_ETC1_RGB,
        RL_PIXELFORMAT_COMPRESSED_ETC2_RGB,
        RL_PIXELFORMAT_COMPRESSED_ETC2_EAC_RGBA,
        RL_PIXELFORMAT_COMPRESSED_PVRT_RGB,
        RL_PIXELFORMAT_COMPRESSED_PVRT_RGBA,
        RL_PIXELFORMAT_COMPRESSED_ASTC_4x4_RGBA,
        RL_PIXELFORMAT_COMPRESSED_ASTC_8x8_RGBA,
    }
}
