// Copyright ©️ Raylib-CsLo and Contributors.
// This file is licensed to you under the MPL-2.0.
// See the LICENSE file in the project root for more info.
// The code and 100+ examples are here! https://github.com/NotNotTech/Raylib-CsLo

// Warning This file is auto generated and changes will be lost

namespace Raylib_CsLo;

/// <summary> Icons enumeration </summary>
public enum GuiIconName
{
    /// <summary>  </summary>
    RiconNone = 0,
    /// <summary>  </summary>
    RiconFolderFileOpen = 1,
    /// <summary>  </summary>
    RiconFileSaveClassic = 2,
    /// <summary>  </summary>
    RiconFolderOpen = 3,
    /// <summary>  </summary>
    RiconFolderSave = 4,
    /// <summary>  </summary>
    RiconFileOpen = 5,
    /// <summary>  </summary>
    RiconFileSave = 6,
    /// <summary>  </summary>
    RiconFileExport = 7,
    /// <summary>  </summary>
    RiconFileNew = 8,
    /// <summary>  </summary>
    RiconFileDelete = 9,
    /// <summary>  </summary>
    RiconFiletypeText = 10,
    /// <summary>  </summary>
    RiconFiletypeAudio = 11,
    /// <summary>  </summary>
    RiconFiletypeImage = 12,
    /// <summary>  </summary>
    RiconFiletypePlay = 13,
    /// <summary>  </summary>
    RiconFiletypeVideo = 14,
    /// <summary>  </summary>
    RiconFiletypeInfo = 15,
    /// <summary>  </summary>
    RiconFileCopy = 16,
    /// <summary>  </summary>
    RiconFileCut = 17,
    /// <summary>  </summary>
    RiconFilePaste = 18,
    /// <summary>  </summary>
    RiconCursorHand = 19,
    /// <summary>  </summary>
    RiconCursorPointer = 20,
    /// <summary>  </summary>
    RiconCursorClassic = 21,
    /// <summary>  </summary>
    RiconPencil = 22,
    /// <summary>  </summary>
    RiconPencilBig = 23,
    /// <summary>  </summary>
    RiconBrushClassic = 24,
    /// <summary>  </summary>
    RiconBrushPainter = 25,
    /// <summary>  </summary>
    RiconWaterDrop = 26,
    /// <summary>  </summary>
    RiconColorPicker = 27,
    /// <summary>  </summary>
    RiconRubber = 28,
    /// <summary>  </summary>
    RiconColorBucket = 29,
    /// <summary>  </summary>
    RiconTextT = 30,
    /// <summary>  </summary>
    RiconTextA = 31,
    /// <summary>  </summary>
    RiconScale = 32,
    /// <summary>  </summary>
    RiconResize = 33,
    /// <summary>  </summary>
    RiconFilterPoint = 34,
    /// <summary>  </summary>
    RiconFilterBilinear = 35,
    /// <summary>  </summary>
    RiconCrop = 36,
    /// <summary>  </summary>
    RiconCropAlpha = 37,
    /// <summary>  </summary>
    RiconSquareToggle = 38,
    /// <summary>  </summary>
    RiconSymmetry = 39,
    /// <summary>  </summary>
    RiconSymmetryHorizontal = 40,
    /// <summary>  </summary>
    RiconSymmetryVertical = 41,
    /// <summary>  </summary>
    RiconLens = 42,
    /// <summary>  </summary>
    RiconLensBig = 43,
    /// <summary>  </summary>
    RiconEyeOn = 44,
    /// <summary>  </summary>
    RiconEyeOff = 45,
    /// <summary>  </summary>
    RiconFilterTop = 46,
    /// <summary>  </summary>
    RiconFilter = 47,
    /// <summary>  </summary>
    RiconTargetPoint = 48,
    /// <summary>  </summary>
    RiconTargetSmall = 49,
    /// <summary>  </summary>
    RiconTargetBig = 50,
    /// <summary>  </summary>
    RiconTargetMove = 51,
    /// <summary>  </summary>
    RiconCursorMove = 52,
    /// <summary>  </summary>
    RiconCursorScale = 53,
    /// <summary>  </summary>
    RiconCursorScaleRight = 54,
    /// <summary>  </summary>
    RiconCursorScaleLeft = 55,
    /// <summary>  </summary>
    RiconUndo = 56,
    /// <summary>  </summary>
    RiconRedo = 57,
    /// <summary>  </summary>
    RiconReredo = 58,
    /// <summary>  </summary>
    RiconMutate = 59,
    /// <summary>  </summary>
    RiconRotate = 60,
    /// <summary>  </summary>
    RiconRepeat = 61,
    /// <summary>  </summary>
    RiconShuffle = 62,
    /// <summary>  </summary>
    RiconEmptybox = 63,
    /// <summary>  </summary>
    RiconTarget = 64,
    /// <summary>  </summary>
    RiconTargetSmallFill = 65,
    /// <summary>  </summary>
    RiconTargetBigFill = 66,
    /// <summary>  </summary>
    RiconTargetMoveFill = 67,
    /// <summary>  </summary>
    RiconCursorMoveFill = 68,
    /// <summary>  </summary>
    RiconCursorScaleFill = 69,
    /// <summary>  </summary>
    RiconCursorScaleRightFill = 70,
    /// <summary>  </summary>
    RiconCursorScaleLeftFill = 71,
    /// <summary>  </summary>
    RiconUndoFill = 72,
    /// <summary>  </summary>
    RiconRedoFill = 73,
    /// <summary>  </summary>
    RiconReredoFill = 74,
    /// <summary>  </summary>
    RiconMutateFill = 75,
    /// <summary>  </summary>
    RiconRotateFill = 76,
    /// <summary>  </summary>
    RiconRepeatFill = 77,
    /// <summary>  </summary>
    RiconShuffleFill = 78,
    /// <summary>  </summary>
    RiconEmptyboxSmall = 79,
    /// <summary>  </summary>
    RiconBox = 80,
    /// <summary>  </summary>
    RiconBoxTop = 81,
    /// <summary>  </summary>
    RiconBoxTopRight = 82,
    /// <summary>  </summary>
    RiconBoxRight = 83,
    /// <summary>  </summary>
    RiconBoxBottomRight = 84,
    /// <summary>  </summary>
    RiconBoxBottom = 85,
    /// <summary>  </summary>
    RiconBoxBottomLeft = 86,
    /// <summary>  </summary>
    RiconBoxLeft = 87,
    /// <summary>  </summary>
    RiconBoxTopLeft = 88,
    /// <summary>  </summary>
    RiconBoxCenter = 89,
    /// <summary>  </summary>
    RiconBoxCircleMask = 90,
    /// <summary>  </summary>
    RiconPot = 91,
    /// <summary>  </summary>
    RiconAlphaMultiply = 92,
    /// <summary>  </summary>
    RiconAlphaClear = 93,
    /// <summary>  </summary>
    RiconDithering = 94,
    /// <summary>  </summary>
    RiconMipmaps = 95,
    /// <summary>  </summary>
    RiconBoxGrid = 96,
    /// <summary>  </summary>
    RiconGrid = 97,
    /// <summary>  </summary>
    RiconBoxCornersSmall = 98,
    /// <summary>  </summary>
    RiconBoxCornersBig = 99,
    /// <summary>  </summary>
    RiconFourBoxes = 100,
    /// <summary>  </summary>
    RiconGridFill = 101,
    /// <summary>  </summary>
    RiconBoxMultisize = 102,
    /// <summary>  </summary>
    RiconZoomSmall = 103,
    /// <summary>  </summary>
    RiconZoomMedium = 104,
    /// <summary>  </summary>
    RiconZoomBig = 105,
    /// <summary>  </summary>
    RiconZoomAll = 106,
    /// <summary>  </summary>
    RiconZoomCenter = 107,
    /// <summary>  </summary>
    RiconBoxDotsSmall = 108,
    /// <summary>  </summary>
    RiconBoxDotsBig = 109,
    /// <summary>  </summary>
    RiconBoxConcentric = 110,
    /// <summary>  </summary>
    RiconBoxGridBig = 111,
    /// <summary>  </summary>
    RiconOkTick = 112,
    /// <summary>  </summary>
    RiconCross = 113,
    /// <summary>  </summary>
    RiconArrowLeft = 114,
    /// <summary>  </summary>
    RiconArrowRight = 115,
    /// <summary>  </summary>
    RiconArrowDown = 116,
    /// <summary>  </summary>
    RiconArrowUp = 117,
    /// <summary>  </summary>
    RiconArrowLeftFill = 118,
    /// <summary>  </summary>
    RiconArrowRightFill = 119,
    /// <summary>  </summary>
    RiconArrowDownFill = 120,
    /// <summary>  </summary>
    RiconArrowUpFill = 121,
    /// <summary>  </summary>
    RiconAudio = 122,
    /// <summary>  </summary>
    RiconFx = 123,
    /// <summary>  </summary>
    RiconWave = 124,
    /// <summary>  </summary>
    RiconWaveSinus = 125,
    /// <summary>  </summary>
    RiconWaveSquare = 126,
    /// <summary>  </summary>
    RiconWaveTriangular = 127,
    /// <summary>  </summary>
    RiconCrossSmall = 128,
    /// <summary>  </summary>
    RiconPlayerPrevious = 129,
    /// <summary>  </summary>
    RiconPlayerPlayBack = 130,
    /// <summary>  </summary>
    RiconPlayerPlay = 131,
    /// <summary>  </summary>
    RiconPlayerPause = 132,
    /// <summary>  </summary>
    RiconPlayerStop = 133,
    /// <summary>  </summary>
    RiconPlayerNext = 134,
    /// <summary>  </summary>
    RiconPlayerRecord = 135,
    /// <summary>  </summary>
    RiconMagnet = 136,
    /// <summary>  </summary>
    RiconLockClose = 137,
    /// <summary>  </summary>
    RiconLockOpen = 138,
    /// <summary>  </summary>
    RiconClock = 139,
    /// <summary>  </summary>
    RiconTools = 140,
    /// <summary>  </summary>
    RiconGear = 141,
    /// <summary>  </summary>
    RiconGearBig = 142,
    /// <summary>  </summary>
    RiconBin = 143,
    /// <summary>  </summary>
    RiconHandPointer = 144,
    /// <summary>  </summary>
    RiconLaser = 145,
    /// <summary>  </summary>
    RiconCoin = 146,
    /// <summary>  </summary>
    RiconExplosion = 147,
    /// <summary>  </summary>
    Ricon1up = 148,
    /// <summary>  </summary>
    RiconPlayer = 149,
    /// <summary>  </summary>
    RiconPlayerJump = 150,
    /// <summary>  </summary>
    RiconKey = 151,
    /// <summary>  </summary>
    RiconDemon = 152,
    /// <summary>  </summary>
    RiconTextPopup = 153,
    /// <summary>  </summary>
    RiconGearEx = 154,
    /// <summary>  </summary>
    RiconCrack = 155,
    /// <summary>  </summary>
    RiconCrackPoints = 156,
    /// <summary>  </summary>
    RiconStar = 157,
    /// <summary>  </summary>
    RiconDoor = 158,
    /// <summary>  </summary>
    RiconExit = 159,
    /// <summary>  </summary>
    RiconMode2d = 160,
    /// <summary>  </summary>
    RiconMode3d = 161,
    /// <summary>  </summary>
    RiconCube = 162,
    /// <summary>  </summary>
    RiconCubeFaceTop = 163,
    /// <summary>  </summary>
    RiconCubeFaceLeft = 164,
    /// <summary>  </summary>
    RiconCubeFaceFront = 165,
    /// <summary>  </summary>
    RiconCubeFaceBottom = 166,
    /// <summary>  </summary>
    RiconCubeFaceRight = 167,
    /// <summary>  </summary>
    RiconCubeFaceBack = 168,
    /// <summary>  </summary>
    RiconCamera = 169,
    /// <summary>  </summary>
    RiconSpecial = 170,
    /// <summary>  </summary>
    RiconLinkNet = 171,
    /// <summary>  </summary>
    RiconLinkBoxes = 172,
    /// <summary>  </summary>
    RiconLinkMulti = 173,
    /// <summary>  </summary>
    RiconLink = 174,
    /// <summary>  </summary>
    RiconLinkBroke = 175,
    /// <summary>  </summary>
    RiconTextNotes = 176,
    /// <summary>  </summary>
    RiconNotebook = 177,
    /// <summary>  </summary>
    RiconSuitcase = 178,
    /// <summary>  </summary>
    RiconSuitcaseZip = 179,
    /// <summary>  </summary>
    RiconMailbox = 180,
    /// <summary>  </summary>
    RiconMonitor = 181,
    /// <summary>  </summary>
    RiconPrinter = 182,
    /// <summary>  </summary>
    RiconPhotoCamera = 183,
    /// <summary>  </summary>
    RiconPhotoCameraFlash = 184,
    /// <summary>  </summary>
    RiconHouse = 185,
    /// <summary>  </summary>
    RiconHeart = 186,
    /// <summary>  </summary>
    RiconCorner = 187,
    /// <summary>  </summary>
    RiconVerticalBars = 188,
    /// <summary>  </summary>
    RiconVerticalBarsFill = 189,
    /// <summary>  </summary>
    RiconLifeBars = 190,
    /// <summary>  </summary>
    RiconInfo = 191,
    /// <summary>  </summary>
    RiconCrossline = 192,
    /// <summary>  </summary>
    RiconHelp = 193,
    /// <summary>  </summary>
    RiconFiletypeAlpha = 194,
    /// <summary>  </summary>
    RiconFiletypeHome = 195,
    /// <summary>  </summary>
    RiconLayersVisible = 196,
    /// <summary>  </summary>
    RiconLayers = 197,
    /// <summary>  </summary>
    RiconWindow = 198,
    /// <summary>  </summary>
    RiconHidpi = 199,
    /// <summary>  </summary>
    Ricon200 = 200,
    /// <summary>  </summary>
    Ricon201 = 201,
    /// <summary>  </summary>
    Ricon202 = 202,
    /// <summary>  </summary>
    Ricon203 = 203,
    /// <summary>  </summary>
    Ricon204 = 204,
    /// <summary>  </summary>
    Ricon205 = 205,
    /// <summary>  </summary>
    Ricon206 = 206,
    /// <summary>  </summary>
    Ricon207 = 207,
    /// <summary>  </summary>
    Ricon208 = 208,
    /// <summary>  </summary>
    Ricon209 = 209,
    /// <summary>  </summary>
    Ricon210 = 210,
    /// <summary>  </summary>
    Ricon211 = 211,
    /// <summary>  </summary>
    Ricon212 = 212,
    /// <summary>  </summary>
    Ricon213 = 213,
    /// <summary>  </summary>
    Ricon214 = 214,
    /// <summary>  </summary>
    Ricon215 = 215,
    /// <summary>  </summary>
    Ricon216 = 216,
    /// <summary>  </summary>
    Ricon217 = 217,
    /// <summary>  </summary>
    Ricon218 = 218,
    /// <summary>  </summary>
    Ricon219 = 219,
    /// <summary>  </summary>
    Ricon220 = 220,
    /// <summary>  </summary>
    Ricon221 = 221,
    /// <summary>  </summary>
    Ricon222 = 222,
    /// <summary>  </summary>
    Ricon223 = 223,
    /// <summary>  </summary>
    Ricon224 = 224,
    /// <summary>  </summary>
    Ricon225 = 225,
    /// <summary>  </summary>
    Ricon226 = 226,
    /// <summary>  </summary>
    Ricon227 = 227,
    /// <summary>  </summary>
    Ricon228 = 228,
    /// <summary>  </summary>
    Ricon229 = 229,
    /// <summary>  </summary>
    Ricon230 = 230,
    /// <summary>  </summary>
    Ricon231 = 231,
    /// <summary>  </summary>
    Ricon232 = 232,
    /// <summary>  </summary>
    Ricon233 = 233,
    /// <summary>  </summary>
    Ricon234 = 234,
    /// <summary>  </summary>
    Ricon235 = 235,
    /// <summary>  </summary>
    Ricon236 = 236,
    /// <summary>  </summary>
    Ricon237 = 237,
    /// <summary>  </summary>
    Ricon238 = 238,
    /// <summary>  </summary>
    Ricon239 = 239,
    /// <summary>  </summary>
    Ricon240 = 240,
    /// <summary>  </summary>
    Ricon241 = 241,
    /// <summary>  </summary>
    Ricon242 = 242,
    /// <summary>  </summary>
    Ricon243 = 243,
    /// <summary>  </summary>
    Ricon244 = 244,
    /// <summary>  </summary>
    Ricon245 = 245,
    /// <summary>  </summary>
    Ricon246 = 246,
    /// <summary>  </summary>
    Ricon247 = 247,
    /// <summary>  </summary>
    Ricon248 = 248,
    /// <summary>  </summary>
    Ricon249 = 249,
    /// <summary>  </summary>
    Ricon250 = 250,
    /// <summary>  </summary>
    Ricon251 = 251,
    /// <summary>  </summary>
    Ricon252 = 252,
    /// <summary>  </summary>
    Ricon253 = 253,
    /// <summary>  </summary>
    Ricon254 = 254,
    /// <summary>  </summary>
    Ricon255 = 255,
}
